python query_gpt.py task_name=logic nesting=1 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=2 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=3 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=4 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=5 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=6 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=7 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=8 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=9 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=10 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=11 batch_from=0 bs=100
python query_gpt.py task_name=logic nesting=12 batch_from=0 bs=100
